### ISSUE TITLE
milliseconds没有数值

### ISSUE THREAD

**Issue by xmsz** [fengyuanchen/vue-countdown#1]
```
time: 1070066867
<countdown ref="countdown" :time="countdown['time']">
                        <template slot-scope="props">
                            <span class="num din" v-text="props.hours" />时
                            <span class="num din" v-text="props.minutes" />分
                            <span class="num din" v-text="props.seconds" />秒
                            <span class="num din" v-text="props.milliseconds" />毫秒
                        </template>
                    </countdown>
```
实际只有时、分、秒在动，而毫米一直是『867』

**Comment by xmsz** [comment]
还遇到了几个情况
第一个是，设置auto-start = fasle后

在mounted里 this.$refs.countdown.start(); 没有效果
 await this.$nextTick();
this.$refs.countdown.start();  没有效果

    setTimeout(() => {
        this.$refs.countdown.start();
      }, 0);
没有效果

必须，这样
```
<countdown v-if="enable" ref="countdown" :time="countdown['time']"/>
setTimeout(() => {
        enable = true
      }, 0);
```
才会启动


第二个情况：
动态赋值:time="countdown['time']" 也是没有效果的，我猜还是和上面问题一样

**Comment by fengyuanchen** [comment]
对于 milliseconds 没有变化的问题，是因为 interval 默认值为 1000，也就是每秒变化一次，毫秒是不会变的，你可以试试将 nterval 设为 100，再看效果。

**Comment by fengyuanchen** [comment]
对于`auto-start="false"`的问题，请看这个示例：https://codepen.io/cfy/pen/GwZpVP

**Comment by xmsz** [comment]
非常感谢
