### ISSUE TITLE
What the bug??

### ISSUE THREAD

**Issue by ThunderBirdsX3** [fengyuanchen/vue-countdown#10]
You should watch this [Video](https://www.facebook.com/ThunderBirdsNo.XIII/posts/1557173934344322?pnref=story) 

I used `this.$refs.countdownBid.count = 10000;` when hit a button.

Seem like error when back to the page, It will get first count time.

file `package.json` used in laravel project.
```
{
    ...
    "devDependencies": {
        "@xkeshi/vue-countdown": "^0.4.0",
        "axios": "^0.16.2",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.0.5",
        "jquery": "^3.2.1",
        "laravel-mix": "^1.4.5",
        "lodash": "^4.17.4",
        "moment": "^2.18.1",
        "vue": "^2.4.4"
    },
    ...
}
```

With `v0.3.0` there was no this bug or error.

**Comment by ThunderBirdsX3** [comment]
Ahhhh!!! Add `this.$refs.countdownBid.endTime = Date.now() + 10000;` after `this.$refs.countdownBid.count = 10000;` will not get this issue. 

But it have some thing I observe, It about refocus page `window.addEventListener('focus', this.onFocus = this.update.bind(this));` if I set `interval = 1000` it would see some different in countdown when refocus page.

**Comment by fengyuanchen** [comment]
The `count` is an internal property, please don't use or change it outside.

**Comment by ThunderBirdsX3** [comment]
@fengyuanchen How can I do. `this.$refs.countdownBid.time = 10000;`?

Or change 
```
this.$refs.countdownBid.count = 10000;
this.$refs.countdownBid.endTime = Date.now() + 10000;
```
To
```
this.$refs.countdownBid.init();
```

Countdown template
```
<countdown v-if="counting" :time="count" :interval="100" tag="p" @countdownend="bidEnd" ref="countdownBid">
    <template scope="props">
        <h1 class="counting">{{ props.seconds }}</h1>
    </template>
</countdown>
```

**Comment by fengyuanchen** [comment]
Why not just change the `time` property?!

**Comment by ThunderBirdsX3** [comment]
@fengyuanchen Nope it does not work.
