### ISSUE TITLE
$emit in "step" method can cause the browser to hang

### ISSUE THREAD

**Issue by badcom** [fengyuanchen/vue-countdown#11]
This "$emit" in the "step" method can cause the browser to hang and crash Vue Devtools if you have multiple countdown components in the same page (maybe even with 1 countdown depending on the "interval" that you set):

https://github.com/xkeshi/vue-countdown/blob/f0c3040d754a0e3d8d0a44480fc7ed9d898ce8b7/src/index.js#L236

**Comment by fengyuanchen** [comment]
Any idea? Remove this event?

**Comment by badcom** [comment]
Well, having the "progress" might be useful in some cases and in my case I needed this, so I removed the $emit and used a global variable (shared state). Perhaps you could pass this variable as a prop?

Also, since I have multiple countdown components in the same page, I also had to pass a "index" through props to the countdown so that I can manage them separately, so in the case of the global variable, I passed it as an array and did `store.remainingTime[this.index] = remainingTime`

**Comment by fengyuanchen** [comment]
@badcom Currently, if you don't need these events, you can set the `emit-event` prop to `false` to disable these events.
