### ISSUE TITLE
reset() function is not supported

### ISSUE THREAD

**Issue by arsen-s** [fengyuanchen/vue-countdown#19]
I can't reset the timer

**Comment by fengyuanchen** [comment]
Just re-render the countdown component with `v-if` directive.

**Comment by luismartinezs** [comment]
What about something like this?
```
     <vue-countdown
        :key="visible"
        @end="visible = !visible"
        ...
      >
        {{ slotProps.minutes }}:{{ slotProps.seconds }}
      </vue-countdown>
```

Visible is just a boolean. Setting a key will force it to instantly re-render without having to worry about fallback HTML
