### ISSUE TITLE
safari浏览器出现报错

### ISSUE THREAD

**Issue by sitting2002** [fengyuanchen/vue-countdown#2]
safari浏览器出现报错，如下图。
chrome以及firefox未见有此报错，正常

safari Version 12.0 (14606.1.36.1.9)
chrome Version 70.0.3538.110 (Official Build) (64-bit)
firefox 63.0.3 (64 位)

![image](https://user-images.githubusercontent.com/6848625/49051520-2eef1e00-f223-11e8-94aa-f2371f3a2851.png)

**Comment by sitting2002** [comment]
![image](https://user-images.githubusercontent.com/6848625/49323823-ca063180-f55c-11e8-9b08-704b1f15403c.png)
我把你readme 的例子直接拷上去  也是同样的报错啊。

**Comment by fengyuanchen** [comment]
在 Safari 中无法复现。

> 试试这个Demo: https://codepen.io/cfy/pen/GwZpVP
