### ISSUE TITLE
this.$refs.countdown.start is not a function

### ISSUE THREAD

**Issue by Altoar** [fengyuanchen/vue-countdown#20]
Why do I get this error when I try to do the start() method:
Uncaught TypeError: this.$refs.countdown.start is not a function
When I console.log(this.$refs.countdown) I get the VueComponent of the Countdown successfully.

`<countdown :auto-start="false" :time="7000" @countdownend="countdownend()" ref="countdown">
<template slot-scope="props" v-if="props.totalSeconds!=0">{{ props.totalSeconds }}</template>
</countdown>`

Vue method:
`            startcountdown(){
                console.log(this.$refs.countdown);
                this.$refs.countdown.start();
            },`

**Comment by fengyuanchen** [comment]
Please check your code carefully.

**Comment by Altoar** [comment]
It seems to be that this problem is occuring when I load the countdown component dynamically inside  a for loop.

example:
```
<div  v-for="index in [1,2,3]" v-bind:key="index"> 
<countdown v-bind:auto-start="false"  :ref="'countdown'+index" :time="7000"><template slot-scope="props">{{ props.totalSeconds }}</template></countdown>
 </div>

```

and the start method doesn't work.  e.g. this.$refs.countdown1.start()
But outside of the loop it works fine.

**Comment by fengyuanchen** [comment]
> When `ref` is used together with `v-for`, the ref you get will be an array containing the child components mirroring the data source. see [more](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements
).

Demo:

```html
<template>
  <div>
    <div v-for="index in [1, 2, 3]" :key="index"> 
      <countdown :auto-start="false" ref="countdown" :time="7000">
        <template slot-scope="props">{{ props.totalSeconds }}</template>
      </countdown>
    </div>
  </div>
</template>

<script>
  export default {
    mounted() {
      console.log(this.$refs.countdown[1])
    },
  }
</script>
```
