### ISSUE TITLE
countdownend fired when reaching -1

### ISSUE THREAD

**Issue by dasmikko** [fengyuanchen/vue-countdown#24]
I'm experiencing an issue where the `countdownend` is first fired when the countdown reaches **-1**

I don't know if this is to be expected, but to me it seems like a bug.

**Comment by fengyuanchen** [comment]
What's your using case? Any online demo?

**Comment by dylanmcgowan** [comment]
I'm actually running into the same exact thing

```
<vue-countdown
    :time="fromNow"
    :interval="1000"
    @countdownend="status = 'live'"
>
     <template slot-scope="props">
       {{props.days}}d {{props.hours}}h {{props.minutes}}m {{props.seconds}}s
     </template>
</vue-countdown>
```

The interaction does seem like a bug.  When the timer ends all the props switch to -1 then go back to zero. @countdownend doesn't fire until it goes back to 0 from -1.

![countdown bug](https://user-images.githubusercontent.com/4494364/44673707-505d2580-a9fa-11e8-9080-7e7f543f07a4.gif)

**Comment by dasmikko** [comment]
Thanks @dylanmcgowan this is exactly what I'm talking about.

**Comment by SIDDU-FED** [comment]
how add event when it reaches 0 seconds
