### ISSUE TITLE
any way to remove the microsecond

### ISSUE THREAD

**Issue by saamalam** [fengyuanchen/vue-countdown#25]
is there any way to remove the last microsecond timer. only want up to plain minutes not any microseconds digit??

**Comment by fengyuanchen** [comment]
Just don't put it into your html.

**Comment by saamalam** [comment]
import VueCountdown from '@xkeshi/vue-countdown';

`<VueCountdown :time="new Date(market.end_date) - new Date()" :interval="100" tag="p">
                                <template slot-scope="props"><i class="fa fa-clock-o"></i> {{ props.days }}d {{ props.hours }}:{{ props.minutes }}:{{ props.seconds }}</template>
                              </VueCountdown>`

is there any way we could remove ms from props.seconds, need only to keep the seconds

**Comment by fengyuanchen** [comment]
Set the `interval` prop to `1000` (default value).
