### ISSUE TITLE
How to 'restart' the countdown?

### ISSUE THREAD

**Issue by patrickbolle** [fengyuanchen/vue-countdown#3]
Hi there! Thanks so much for this. Nice and easy.

How would I go about restarting the timer. Eg, bring the time back to the originally input date?

Cheers!

**Comment by fengyuanchen** [comment]
Just use `v-if` to enable or disable a countdown:

```html
<countdown v-if="start"></countdown>
```

**Comment by insub** [comment]
@patrickbolle
 `this.$refs.countdown.init();`

**Comment by ermst4r** [comment]
for other ppl. this did the trick for me.

```    
let self = this;
self.$refs.countdown.end();
self.$refs.countdown.totalMilliseconds =  10000;
self.$refs.countdown.start(); 

```
