### ISSUE TITLE
能不能加一个活动倒计时，包括预热的例子

### ISSUE THREAD

**Issue by wangyupo** [fengyuanchen/vue-countdown#30]
用在活动预售页面上，如：
“距离开售还有xx天xx时xx分”，到了开售时间变成“距离结束还有xx天xx时xx分”，结束以后再变成“活动结束”。
有3个事件——未开始，进行中，已结束

**Comment by fengyuanchen** [comment]
没有通用性。你在自己业务中自己定义就是了。
