### ISSUE TITLE
How to countdown on fixed date?

### ISSUE THREAD

**Issue by nabeelatsanaulla** [fengyuanchen/vue-countdown#32]
Right now from the example the timer starts when the page loads. I want the countdown to minus from a fixed date. for example the date is 29th feb ... so how can i mention date as 28 feb - now. to get the proper countdown going. thanks.

**Comment by nabeelatsanaulla** [comment]
Got it I set the date using vanilla javascript. thanks.

**Comment by dwicahyo-dev** [comment]
Hi there, how was it works ? Could you please share your thoughts here ?. Thanks
