### ISSUE TITLE
data.totalMilliseconds is undefined

### ISSUE THREAD

**Issue by aseredenko** [fengyuanchen/vue-countdown#34]
I noticed that the component doesn't have the ability to get data.totalMilliseconds (although it was listed in documentation). Screenshot of data object below

<img width="500" alt="Screenshot 2019-04-09 at 21 56 46" src="https://user-images.githubusercontent.com/6630181/55827310-8fb42e80-5b12-11e9-9a84-0e5afb36179b.png">

**Comment by fengyuanchen** [comment]
Which version you are using?

**Comment by fengyuanchen** [comment]
Works fine in the official demo: https://fengyuanchen.github.io/vue-countdown/

**Comment by aseredenko** [comment]
I've used this script https://github.com/fengyuanchen/vue-countdown/blob/master/dist/vue-countdown.min.js

**Comment by aseredenko** [comment]
@fengyuanchen It happens when I'm using @progress="handleCountdownProgress", I don't see that in the demo
