### ISSUE TITLE
how to add end date ?

### ISSUE THREAD

**Issue by webafra** [fengyuanchen/vue-countdown#36]
hi .

i want add a date time to counting down .
can use this ?

for example : 
`
<countdown :timestamp="1561059000">
  <template slot-scope="props">Time Remaining：{{ props.days }} days, {{ props.hours }} hours, {{ props.minutes }} minutes, {{ props.seconds }} seconds.</template>
</countdown>
`

**Comment by fengyuanchen** [comment]
The right prop is `time` not `timestamp`.

**Comment by webafra** [comment]
Yes, I know this.
I want to enter a value by date to calculate.

example : 
2019-06-25 23:00:00
or : 
timestamp date

**Comment by fengyuanchen** [comment]
Not support that. You can try `endTime = Date.now() + time`
