### ISSUE TITLE
Wrong behavior in handleVisibilityChange method

### ISSUE THREAD

**Issue by pickmecoach** [fengyuanchen/vue-countdown#37]
Hi!
I noticed, if you open the demo **in a new tab** and then switch to it, we get a duplicate **update** call, and it turns out that the **progress** event emits twice per **interval**.
**Remark:** it's not every time behavior, but it's shows up from time to time.

**Comment by fengyuanchen** [comment]
Do you mean the [official demo](https://fengyuanchen.github.io/vue-countdown/)? 

> Please note that there are two working countdown instances in the demo page.

**Comment by pickmecoach** [comment]
Yep. Well, If you delete all instances except  the second one, the result will be the same

**Comment by fengyuanchen** [comment]
Got it. Thanks!
