### ISSUE TITLE
End event on different tab

### ISSUE THREAD

**Issue by ZuggieTM** [fengyuanchen/vue-countdown#38]
If I have a countdown running and tab to a different browser tab, the end event doesn't fire before I tab back.

Is there a way to make it fire even if I'm not on the tab, when the countdown ends?

**Comment by fengyuanchen** [comment]
When you switch to another tab, the countdown in the current tab will be paused for better performance. So the end event will not be fired before you switch back.

**Comment by ZuggieTM** [comment]
Ah okay. That's unfortunate. Would have been a nice feature to let it run. I made a workaround with setTimeout instead. Thanks!
