### ISSUE TITLE
Does the countdown stop when user navigates away from the page?

### ISSUE THREAD

**Issue by patrickbolle** [fengyuanchen/vue-countdown#4]
Me once again!
Is this just me or, does the timer stop counting down when the user navigates to another page?

I'm building a little pomodoro timer and need the timer to keep going!

Thanks.

**Comment by fengyuanchen** [comment]
Of course! The countdown will be stoped automatically [`beforeDestroy`](https://vuejs.org/v2/api/#beforeDestroy).

**Comment by patrickbolle** [comment]
Okay! So how can I keep the timer going when the user exits the page? Cheers!

**Comment by fengyuanchen** [comment]
Time is going always...
