### ISSUE TITLE
:auto-start="false" bug

### ISSUE THREAD

**Issue by Photoshopper** [fengyuanchen/vue-countdown#47]
For example: I have a countdown time set for 2 minutes. I start the countdown after 30 seconds and then switch to another tab and go back to countdown immediately, and instead of seeing about 2 minutes left I see 1 minute 30 seconds.

I added endTime and totalMilliseconds at the beginning of the start function. It seems like fixes the problem

```
start: function start() {
    this.totalMilliseconds = this.time;
    this.endTime = this.now() + this.time;
...
}
```

**Comment by fengyuanchen** [comment]
It is not a bug. For your case, you should set the `now` prop to your initial time.

```html
<countdown :now="now">...</countdown>
```

```js
const now = Date.now();

export default {
  // ...
  methods: {
    now: function () {
      // Always return a fixed time.
      return now;
    },
  },
};
```

**Comment by Photoshopper** [comment]
> It is not a bug. For your case, you should set the now prop to your initial time.

In this case, countdown always starts again from the same value when I switch back from another tab.

For example:
start from 00:00:30
switch to another tab 00:00:25
switch back 00:00:30

**Comment by fengyuanchen** [comment]
May not support your case. Try other components, please.
