### ISSUE TITLE
Feature request: count up when reaches 0h0m0s

### ISSUE THREAD

**Issue by badcom** [fengyuanchen/vue-countdown#6]
Do you intend to implement this? Perhaps having a property "elapse" where if it's true, the timer starts counting up when it reaches 0h0m0s.

**Comment by fengyuanchen** [comment]
You may need another vue component such as [vue-countup](https://github.com/samcrosoft/vue-countup).

**Comment by badcom** [comment]
No. I need a component that does both.
Anyways, I've done the changes I needed in your component.

**Comment by fengyuanchen** [comment]
You may have to create a new one by yourself as this is just a **countdown** component.

**Comment by janschoepke** [comment]
@badcom Could you maybe share your adjustments to realize this component to count up after reaching 0:00?
