### ISSUE TITLE
Adds leading zero (v2.0.0-alpha)

### ISSUE THREAD

**Issue by ivanchik1986** [fengyuanchen/vue-countdown#60]
Hello. How do I add a leading zero (v2.0.0-alpha)?
00:00
04:02
01 minute, 05 seconds

**Comment by fengyuanchen** [comment]
Just use the `transform` prop to format the numbers. 

Take the test case as an example: https://github.com/fengyuanchen/vue-countdown/blob/c998a67e5c6b454803510ef1cbb4d180072124f9/tests/props.spec.ts#L238-L260
