### ISSUE TITLE
Make :showHours dynamic

### ISSUE THREAD

**Issue by CristianGrigorita** [fengyuanchen/vue-countdown#62]
Hello, 

I would like to set :showHours based on a variable, something like :showHours="this.hasHours".
this.hasHours is true or false, depending on the time selected by the user.
In my case the countdown can be selected to take only minutes and in this case I don't want to show the hours.

How should I accomplish this, as the countdown does not change dynamically, as it does if I change the time set with :deadline="this.time_end" ?

**Comment by fengyuanchen** [comment]
You can override the hours in the `transform` prop function, for examples:

```js
export default {
  methods: {
    transformSlotProps(props) {
      const formattedProps = {};

      Object.entries(props).forEach(([key, value]) => {
        formattedProps[key] = key === 'hours' ? 0 : value;
      });

      return formattedProps;
    },
  },
};
```
