### ISSUE TITLE
Peer Dependency problem

### ISSUE THREAD

**Issue by allurco** [fengyuanchen/vue-countdown#63]
When I try to install on a new Vue3 project I get:
`
npm ERR! Found: vue@3.0.7  
npm ERR! node_modules/vue  
npm ERR!   vue@"^3.0.0" from the root project
`

I think you are targeting specifically that vue version.

**Comment by fengyuanchen** [comment]
For Vue 3, you must install the `next` tag of version:

```shell
npm install vue@next @chenfengyuan/vue-countdown@next
```
