### ISSUE TITLE
Does not work on Nuxt

### ISSUE THREAD

**Issue by 6ichem** [fengyuanchen/vue-countdown#69]
I keep getting "document is not defined" that leads to this
```
      if (document.visibilityState === 'visible') {
        this.continue();
      }
```
It does not work on Nuxt

**Comment by 6ichem** [comment]
Fixed using `<no-ssr>` tag

**Comment by rwaddin** [comment]
> Fixed using `<no-ssr>` tag

thank's, save my day :)

**Comment by rwaddin** [comment]
> Fixed using `<no-ssr>` tag

thank's :+1:

in nuxt 3 tag `<no-ssr>` will be deprecated, please use tag `<client-only>`
