### ISSUE TITLE
update not working

### ISSUE THREAD

**Issue by SERDARPINAR** [fengyuanchen/vue-countdown#73]
hello..

if i use showzero = false .. countdown not update after rebind end-time..  
forexample : 

show-zero : false....    59 seconds...58 seconds... 
set new end date to 2 minutes..  countdown not showing minutes label...    

how can i do this ?
i hope you undestand me..

**Comment by fengyuanchen** [comment]
Just re-render the component for restarting by the `v-if` directive after the countdown ends.
