### ISSUE TITLE
Is it possible to make the `handleVisibilityChange` listener as prop option ?

### ISSUE THREAD

**Issue by jinevo** [fengyuanchen/vue-countdown#77]
When the countdown is paused, it continues when coming back to the page since it triggers the [handleVisibilityChange](https://github.com/fengyuanchen/vue-countdown/blob/629778d7ab4014035012019891c8277159d63c0f/src/index.ts#L388) callback which continues the countdown under the hood.

Is it possible to make this behavior as optional ?

**Comment by fengyuanchen** [comment]
Why?

**Comment by Waniusza** [comment]
Because it calls `continue()` on counter that was paused by user.

On coming back to page, user expects to keep state of counter just as it was set by him/her
