### ISSUE TITLE
How to show only hours ?

### ISSUE THREAD

**Issue by arieltoledo** [fengyuanchen/vue-countdown#78]
Hi, great plugin ! 
Is anyway I can show only hours left ? if its 2 days, show 48h instead of 1d - 24h

**Comment by fengyuanchen** [comment]
You can customize it by scoped slot: `{{ slotProps.days * 12 + slotProps.hours }} hours`.

**Comment by arieltoledo** [comment]
@fengyuanchen Great thanks ! My bad didn't realize .
