### ISSUE TITLE
[fature-request] Add a restart method

### ISSUE THREAD

**Issue by DannyFeliz** [fengyuanchen/vue-countdown#79]
It would be cool to have a restart method that takes the countdown to the initial time.

**Comment by fengyuanchen** [comment]
You can call the `end` method first, and then call the `start` method to restart.

**Comment by DannyFeliz** [comment]
@fengyuanchen the problem is that I have some actions in the `end` event and I don't want to be executed at least if finished for real.

**Comment by fengyuanchen** [comment]
You can also remount the component.

**Comment by DannyFeliz** [comment]
@fengyuanchen that is not feasible for my use case.

I created a [PR](https://github.com/fengyuanchen/vue-countdown/pull/80) adding the restart method.

**Comment by xiaozi** [comment]
> You can call the `end` method first, and then call the `start` method to restart.

`end` method make `totalMilliseconds` to be zero, then countdown cannot start again using `start` method.

**Comment by fengyuanchen** [comment]
Supports this as of v2.1.0.
