### ISSUE TITLE
[Feature Request] Add universal support for vue 2.7.x + 3.x

### ISSUE THREAD

**Issue by renatodeleao** [fengyuanchen/vue-countdown#82]
Hello 👋  and thanks for the work on this package!

I've looked at the source and it wouldn't be a huge amount of effort to support both versions in the same file instead keeping two branches where v1 doesn't get the updates and so do vue2 consumers.

After the integration of `composition-api` into `vue@2.7.x`, for this component use-case, the path to achieving it basically adding a `Vue` `version` detection boolean is `isVue3` and creating a map of new property names. 

```js
const version = require('vue').version || require('vue').default.version
export const isVue3 = /^3\./.test(version)

export const INSTANCE_PROPERTIES_MAP = {
   beforeUnmount: isVue3 ? 'beforeUnmount' : 'beforeDestroy',
   $slots: isVue3 ? '$slots' : '$scopedSlots'
}
```

```diff
+ import { INSTANCE_PROPERTIES_MAP } from './utils'

export default {
  name: 'VueCountdown',

- beforeUnmount() {},
+ [INSTANCE_PROPERTIES_MAP.beforeUnmount]() {},

  render() {
+   const slots = this[INSTANCE_PROPERTIES_MAP.$slots]

     return slots.default({})
   }
}
```

1. If you wanted to support `2.6`.x I suppose you could get into `vue-demi`, but I've been there and it has its gotchas. 
1. Previous "art" https://github.com/vueuse/vueuse/blob/bc1bd48a99981cd0bca1c8b594aac5c0d0d3f062/packages/shared/utils/compatibility.ts
1. `$scopedSlots` were unified after vue 2.6 so they map to normal slots as well https://github.com/vuejs/rfcs/blob/master/active-rfcs/0006-slots-unification.md#adoption-strategy

Let me know, happy to do a PR if you think would be a nice improvement.

Cheers,
R

**Comment by fengyuanchen** [comment]
Thanks for your suggestion, I would like to keep it as it is currently.

PS: It will be not easy to handle the type declarations for both Vue 2 and Vue 3 as the v2 is written in TypeScript.

**Comment by renatodeleao** [comment]
No problem, thanks for considering it!

> PS: It will be not easy to handle the type declarations for both Vue 2 and Vue 3 as the v2 is written in TypeScript.

Yup, I tried it and had to add a few `// @ts-ignore` around, but I'm not a typescript guru here.
