### ISSUE TITLE
auto-start does not work with Composition API

### ISSUE THREAD

**Issue by ghost** [fengyuanchen/vue-countdown#93]
Hello !

First, thanks for this package !

I'm trying to use the countdown in a project using Composition API. It works pretty well except for the` auto-start` prop.

Let's say I set the time to 1min. My component is mounted, I wait 10 seconds before starting the countdown, I click the start button and the timer jumps from 1min to 50s immediately.

It happens only in Composition API.
```
<template>
    <vue-countdown 
        ref="counter"
        :auto-start="false"
        :time="60000"
        v-slot="{ hours, minutes, seconds }"
    >
            {{ hours }}:{{ minutes }}:{{ seconds }}
    </vue-countdown>

    <button @click="startGame()">Start Countdown</button>

</template>

<script setup lang="ts">
    const counter = ref()

    function startGame(): void {
        counter.value.start()
    }
</script>
```

https://github.com/fengyuanchen/vue-countdown/assets/82037987/1d2b1fc1-15a7-417c-9985-8fb99518bc6d

**Comment by ghost** [comment]
Sadly, this bug is still present after your fix.

I almost find a work-around by passing `() => Date.now()` to the `now` props when I start the timer, but I always lose 2 seconds at the beginning.

**Comment by fengyuanchen** [comment]
> Sadly, this bug is still present after your fix.
> 
> I almost find a work-around by passing `() => Date.now()` to the `now` props when I start the timer, but I always lose 2 seconds at the beginning.

It cannot reproduce. Please check out this demo: https://codepen.io/cfy/pen/oNJLmJq
